[package]
name = "concord-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = "0.24.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4.22"
simple_logger = "5.0.0"
