name: ci

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

env:
  DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ DOCKERHUB_REPOSITORY }}
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ DOCKERHUB_USERNAME }}
          password: ${{ DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}